version:0.2

phases:
  pre_build:
    commands:
        -npm install
      
  build:
     command:
        -npm run build
        
 artifacts:
     files:
       - '**/*
   discard-paths:no
   base-directory:build
   
   
   
   
   
      
